// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRmnd4mNm7a6BBHSBM6okNSc5AKRcYkCU',
    appId: '1:74089913277:web:a2644304215c15192f50d4',
    messagingSenderId: '74089913277',
    projectId: 'reddit-clone-f9e96',
    authDomain: 'reddit-clone-f9e96.firebaseapp.com',
    storageBucket: 'reddit-clone-f9e96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiW_QdGPFw_Hl5qyI2fvfW0elkhF54NwU',
    appId: '1:74089913277:android:20907d4e744907082f50d4',
    messagingSenderId: '74089913277',
    projectId: 'reddit-clone-f9e96',
    storageBucket: 'reddit-clone-f9e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoedPeqD1Ztc8Naoud0pS3DtJnH4hmZdo',
    appId: '1:74089913277:ios:1caca5eafe3f4ddc2f50d4',
    messagingSenderId: '74089913277',
    projectId: 'reddit-clone-f9e96',
    storageBucket: 'reddit-clone-f9e96.firebasestorage.app',
    androidClientId: '74089913277-p0lb3238bbsai7ei09ohpsf326uk59kd.apps.googleusercontent.com',
    iosClientId: '74089913277-1is0705qjv6na0315c07a6de1l6na0ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoedPeqD1Ztc8Naoud0pS3DtJnH4hmZdo',
    appId: '1:74089913277:ios:1caca5eafe3f4ddc2f50d4',
    messagingSenderId: '74089913277',
    projectId: 'reddit-clone-f9e96',
    storageBucket: 'reddit-clone-f9e96.firebasestorage.app',
    androidClientId: '74089913277-p0lb3238bbsai7ei09ohpsf326uk59kd.apps.googleusercontent.com',
    iosClientId: '74089913277-1is0705qjv6na0315c07a6de1l6na0ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRmnd4mNm7a6BBHSBM6okNSc5AKRcYkCU',
    appId: '1:74089913277:web:9c1fa5c8bf50a0022f50d4',
    messagingSenderId: '74089913277',
    projectId: 'reddit-clone-f9e96',
    authDomain: 'reddit-clone-f9e96.firebaseapp.com',
    storageBucket: 'reddit-clone-f9e96.firebasestorage.app',
  );
}
